# **Air Quality**

---
---

# Data preprocessing

In [3]:
# Import of libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlite3 as sql

#### Preparing Data

In [4]:
pd.set_option('display.max_columns', None)

**Load and view all the pollution and weather datasets**

In [5]:
pollution_2020 = pd.read_csv('../data/raw/pollution data/2020.csv', sep = ';')
pollution_2021 = pd.read_csv('../data/raw/pollution data/2021.csv', sep = ';')
pollution_2022 = pd.read_csv('../data/raw/pollution data/2022.csv', sep = ';')
pollution_2023 = pd.read_csv('../data/raw/pollution data/2023.csv', sep = ';')

pollution_2020.head()

,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,h02,v02,h03,v03,h04,v04,h05,v05,h06,v06,h07,v07,h08,v08,h09,v09,h10,v10,h11,v11,h12,v12,h13,v13,h14,v14,h15,v15,h16,v16,h17,v17,h18,v18,h19,v19,h20,v20,h21,v21,h22,v22,h23,v23,h24,v24
0,28,102,1,1,28102001_1_38,2020,1,1,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V
1,28,102,1,6,28102001_6_48,2020,1,1,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,4",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,4",V,"0,4",V,"0,4",V,"0,4",V,"0,4",V,"0,4",V,"0,4",V
2,28,102,1,7,28102001_7_8,2020,1,1,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"2,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V,"1,0",V
3,28,102,1,8,28102001_8_8,2020,1,1,"8,0",V,"8,0",V,"7,0",V,"6,0",V,"6,0",V,"6,0",V,"7,0",V,"6,0",V,"5,0",V,"5,0",V,"5,0",V,"5,0",V,"5,0",V,"5,0",V,"5,0",V,"5,0",V,"6,0",V,"7,0",V,"8,0",V,"8,0",V,"8,0",V,"9,0",V,"10,0",V,"8,0",V
4,28,102,1,10,28102001_10_49,2020,1,1,"8,0",V,"15,0",V,"13,0",V,"11,0",V,"12,0",V,"16,0",V,"17,0",V,"20,0",V,"11,0",V,"2,0",V,"1,0",V,"1,0",V,"9,0",V,"9,0",V,"8,0",V,"7,0",V,"14,0",V,"22,0",V,"22,0",V,"16,0",V,"16,0",V,"17,0",V,"17,0",V,"17,0",V

In [6]:
weather_2020 = pd.read_csv('../data/raw/weather data/2020.csv', sep = ';')
weather_2021 = pd.read_csv('../data/raw/weather data/2021.csv', sep = ';')
weather_2022 = pd.read_csv('../data/raw/weather data/2022.csv', sep = ';')
weather_2023 = pd.read_csv('../data/raw/weather data/2023.csv', sep = ';')

weather_2020.head()

,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,h02,v02,h03,v03,h04,v04,h05,v05,h06,v06,h07,v07,h08,v08,h09,v09,h10,v10,h11,v11,h12,v12,h13,v13,h14,v14,h15,v15,h16,v16,h17,v17,h18,v18,h19,v19,h20,v20,h21,v21,h22,v22,h23,v23,h24,v24
0,28,102,1,81,28102001_81_89,2020,1,1,"1,1",V,1,V,"1,1",V,1,V,"1,2",V,"1,2",V,"1,5",V,"1,6",V,"1,6",V,1,V,"0,4",V,"0,8",V,"1,3",V,"1,6",V,"1,5",V,"0,8",V,"0,8",V,"1,3",V,"0,7",V,"0,2",V,"0,3",V,"0,9",V,"0,7",V,"0,4",V
1,28,102,1,82,28102001_82_89,2020,1,1,15,V,34,V,32,V,26,V,16,V,14,V,40,V,358,V,41,V,26,V,62,V,131,V,171,V,190,V,204,V,299,V,228,V,214,V,232,V,291,V,3,V,359,V,18,V,27,V
2,28,102,1,83,28102001_83_89,2020,1,1,"2,7",V,"2,6",V,"2,1",V,"1,9",V,"1,6",V,"1,6",V,0,V,"0,1",V,2,V,"5,2",V,"8,4",V,"9,8",V,"10,8",V,"12,8",V,"13,7",V,"13,9",V,"11,9",V,"8,6",V,"7,5",V,"7,3",V,"6,3",V,"5,3",V,"4,3",V,"4,2",V
3,28,102,1,86,28102001_86_89,2020,1,1,86,V,87,V,89,V,91,V,92,V,92,V,96,V,96,V,87,V,76,V,65,V,60,V,60,V,53,V,48,V,43,V,53,V,63,V,68,V,68,V,74,V,81,V,86,V,85,V
4,28,102,1,87,28102001_87_89,2020,1,1,946,V,946,V,945,V,945,V,944,V,945,V,946,V,947,V,947,V,948,V,948,V,947,V,945,V,944,V,943,V,943,V,944,V,944,V,944,V,944,V,945,V,945,V,945,V,944,V

In [7]:
# DataFrame dimensions 
print("Dimensions Pollution Data 20:", pollution_2020.shape)
print("Dimensions Weather Data 20:", weather_2020.shape)
print("Dimensions Pollution Data 21:", pollution_2021.shape)
print("Dimensions Weather Data 21:", weather_2021.shape)
print("Dimensions Pollution Data 22:", pollution_2022.shape)
print("Dimensions Weather Data 22:", weather_2022.shape)
print("Dimensions Pollution Data 23:", pollution_2023.shape)
print("Dimensions Weather Data 23:", weather_2023.shape)

Dimensions Pollution Data 20: (58560, 56)
Dimensions Weather Data 20: (61474, 56)
Dimensions Pollution Data 21: (58392, 56)
Dimensions Weather Data 21: (61313, 56)
Dimensions Pollution Data 22: (58293, 56)
Dimensions Weather Data 22: (61306, 56)
Dimensions Pollution Data 23: (63828, 56)
Dimensions Weather Data 23: (68913, 56)

In [8]:
# Detailed information on pollutants
pollution_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58560 entries, 0 to 58559
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   provincia       58560 non-null  int64
 1   municipio       58560 non-null  int64
 2   estacion        58560 non-null  int64
 3   magnitud        58560 non-null  int64
 4   punto_muestreo  58560 non-null  object
 5   ano             58560 non-null  int64
 6   mes             58560 non-null  int64
 7   dia             58560 non-null  int64
 8   h01             58247 non-null  object
 9   v01             58560 non-null  object
 10  h02             58245 non-null  object
 11  v02             58560 non-null  object
 12  h03             58214 non-null  object
 13  v03             58560 non-null  object
 14  h04             58208 non-null  object
 15  v04             58560 non-null  object
 16  h05             58200 non-null  object
 17  v05             58560 non-null  object
 18  h06             57295 non-null  object
 19  v06             58560 non-null  object
 20  h07             56680 non-null  object
 21  v07             58560 non-null  object
 22  h08             56244 non-null  object
 23  v08             58560 non-null  object
 24  h09             55994 non-null  object
 25  v09             58560 non-null  object
 26  h10             55808 non-null  object
 27  v10             58560 non-null  object
 28  h11             55944 non-null  object
 29  v11             58560 non-null  object
 30  h12             56343 non-null  object
 31  v12             58560 non-null  object
 32  h13             57029 non-null  object
 33  v13             58560 non-null  object
 34  h14             57579 non-null  object
 35  v14             58560 non-null  object
 36  h15             57899 non-null  object
 37  v15             58560 non-null  object
 38  h16             58112 non-null  object
 39  v16             58560 non-null  object
 40  h17             58233 non-null  object
 41  v17             58560 non-null  object
 42  h18             58271 non-null  object
 43  v18             58560 non-null  object
 44  h19             58281 non-null  object
 45  v19             58560 non-null  object
 46  h20             58294 non-null  object
 47  v20             58560 non-null  object
 48  h21             58281 non-null  object
 49  v21             58560 non-null  object
 50  h22             58255 non-null  object
 51  v22             58560 non-null  object
 52  h23             58248 non-null  object
 53  v23             58560 non-null  object
 54  h24             58221 non-null  object
 55  v24             58560 non-null  object
dtypes: int64(7), object(49)
memory usage: 25.0+ MB

In [9]:
# Detailed information on weather
weather_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61474 entries, 0 to 61473
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   provincia       61474 non-null  int64
 1   municipio       61474 non-null  int64
 2   estacion        61474 non-null  int64
 3   magnitud        61474 non-null  int64
 4   punto_muestreo  61474 non-null  object
 5   ano             61474 non-null  int64
 6   mes             61474 non-null  int64
 7   dia             61474 non-null  int64
 8   h01             61195 non-null  object
 9   v01             61474 non-null  object
 10  h02             61183 non-null  object
 11  v02             61474 non-null  object
 12  h03             61167 non-null  object
 13  v03             61474 non-null  object
 14  h04             61140 non-null  object
 15  v04             61474 non-null  object
 16  h05             61146 non-null  object
 17  v05             61474 non-null  object
 18  h06             61025 non-null  object
 19  v06             61474 non-null  object
 20  h07             60970 non-null  object
 21  v07             61474 non-null  object
 22  h08             60911 non-null  object
 23  v08             61474 non-null  object
 24  h09             60923 non-null  object
 25  v09             61474 non-null  object
 26  h10             60940 non-null  object
 27  v10             61474 non-null  object
 28  h11             60933 non-null  object
 29  v11             61474 non-null  object
 30  h12             61012 non-null  object
 31  v12             61474 non-null  object
 32  h13             61106 non-null  object
 33  v13             61474 non-null  object
 34  h14             61223 non-null  object
 35  v14             61474 non-null  object
 36  h15             61265 non-null  object
 37  v15             61474 non-null  object
 38  h16             61289 non-null  object
 39  v16             61474 non-null  object
 40  h17             61317 non-null  object
 41  v17             61474 non-null  object
 42  h18             61317 non-null  object
 43  v18             61474 non-null  object
 44  h19             61297 non-null  object
 45  v19             61474 non-null  object
 46  h20             61284 non-null  object
 47  v20             61474 non-null  object
 48  h21             61275 non-null  object
 49  v21             61474 non-null  object
 50  h22             61249 non-null  object
 51  v22             61474 non-null  object
 52  h23             61237 non-null  object
 53  v23             61474 non-null  object
 54  h24             61223 non-null  object
 55  v24             61474 non-null  object
dtypes: int64(7), object(49)
memory usage: 26.3+ MB

In [10]:
# types of pollution data
pollution_2020.dtypes

provincia          int64
municipio          int64
estacion           int64
magnitud           int64
punto_muestreo    object
ano                int64
mes                int64
dia                int64
h01               object
v01               object
h02               object
v02               object
h03               object
v03               object
h04               object
v04               object
h05               object
v05               object
h06               object
v06               object
h07               object
v07               object
h08               object
v08               object
h09               object
v09               object
h10               object
v10               object
h11               object
v11               object
h12               object
v12               object
h13               object
v13               object
h14               object
v14               object
h15               object
v15               object
h16               object
v16               object
h17               object
v17               object
h18               object
v18               object
h19               object
v19               object
h20               object
v20               object
h21               object
v21               object
h22               object
v22               object
h23               object
v23               object
h24               object
v24               object
dtype: object

In [11]:
# Types of weather data
weather_2020.dtypes

provincia          int64
municipio          int64
estacion           int64
magnitud           int64
punto_muestreo    object
ano                int64
mes                int64
dia                int64
h01               object
v01               object
h02               object
v02               object
h03               object
v03               object
h04               object
v04               object
h05               object
v05               object
h06               object
v06               object
h07               object
v07               object
h08               object
v08               object
h09               object
v09               object
h10               object
v10               object
h11               object
v11               object
h12               object
v12               object
h13               object
v13               object
h14               object
v14               object
h15               object
v15               object
h16               object
v16               object
h17               object
v17               object
h18               object
v18               object
h19               object
v19               object
h20               object
v20               object
h21               object
v21               object
h22               object
v22               object
h23               object
v23               object
h24               object
v24               object
dtype: object

In [12]:
pollution_2020.isnull().sum()

provincia            0
municipio            0
estacion             0
magnitud             0
punto_muestreo       0
ano                  0
mes                  0
dia                  0
h01                313
v01                  0
h02                315
v02                  0
h03                346
v03                  0
h04                352
v04                  0
h05                360
v05                  0
h06               1265
v06                  0
h07               1880
v07                  0
h08               2316
v08                  0
h09               2566
v09                  0
h10               2752
v10                  0
h11               2616
v11                  0
h12               2217
v12                  0
h13               1531
v13                  0
h14                981
v14                  0
h15                661
v15                  0
h16                448
v16                  0
h17                327
v17                  0
h18                289
v18                  0
h19                279
v19                  0
h20                266
v20                  0
h21                279
v21                  0
h22                305
v22                  0
h23                312
v23                  0
h24                339
v24                  0
dtype: int64

In [13]:
weather_2020.isnull().sum()

provincia           0
municipio           0
estacion            0
magnitud            0
punto_muestreo      0
ano                 0
mes                 0
dia                 0
h01               279
v01                 0
h02               291
v02                 0
h03               307
v03                 0
h04               334
v04                 0
h05               328
v05                 0
h06               449
v06                 0
h07               504
v07                 0
h08               563
v08                 0
h09               551
v09                 0
h10               534
v10                 0
h11               541
v11                 0
h12               462
v12                 0
h13               368
v13                 0
h14               251
v14                 0
h15               209
v15                 0
h16               185
v16                 0
h17               157
v17                 0
h18               157
v18                 0
h19               177
v19                 0
h20               190
v20                 0
h21               199
v21                 0
h22               225
v22                 0
h23               237
v23                 0
h24               251
v24                 0
dtype: int64

**For greater precision when filtering the data, we create a new column with the unified date and drop the innecesary column**

In [14]:
# Crear una columna 'fecha' con el año, mes y día
pollution_2020['fecha'] = pd.to_datetime(pollution_2020[['ano', 'mes', 'dia']].astype(str).agg('-'.join, axis=1), errors='coerce', format='%Y-%m-%d')
pollution_2020.drop(["ano", "mes", "dia"], axis=1, inplace=True)

weather_2020['fecha'] = pd.to_datetime(weather_2020[['ano', 'mes', 'dia']].astype(str).agg('-'.join, axis=1), errors='coerce', format='%Y-%m-%d')
weather_2020.drop(["ano", "mes", "dia"], axis=1, inplace=True)

In [15]:
pollution_2021['fecha'] = pd.to_datetime(pollution_2021[['ano', 'mes', 'dia']].astype(str).agg('-'.join, axis=1), errors='coerce', format='%Y-%m-%d')
pollution_2021.drop(["ano", "mes", "dia"], axis=1, inplace=True)

weather_2021['fecha'] = pd.to_datetime(weather_2021[['ano', 'mes', 'dia']].astype(str).agg('-'.join, axis=1), errors='coerce', format='%Y-%m-%d')
weather_2021.drop(["ano", "mes", "dia"], axis=1, inplace=True)

In [16]:
pollution_2022['fecha'] = pd.to_datetime(pollution_2022[['ano', 'mes', 'dia']].astype(str).agg('-'.join, axis=1), errors='coerce', format='%Y-%m-%d')
pollution_2022.drop(["ano", "mes", "dia"], axis=1, inplace=True)

weather_2022['fecha'] = pd.to_datetime(weather_2022[['ano', 'mes', 'dia']].astype(str).agg('-'.join, axis=1), errors='coerce', format='%Y-%m-%d')
weather_2022.drop(["ano", "mes", "dia"], axis=1, inplace=True)

In [17]:
pollution_2023['fecha'] = pd.to_datetime(pollution_2023[['ano', 'mes', 'dia']].astype(str).agg('-'.join, axis=1), errors='coerce', format='%Y-%m-%d')
pollution_2023.drop(["ano", "mes", "dia"], axis=1, inplace=True)

weather_2023['fecha'] = pd.to_datetime(weather_2023[['ano', 'mes', 'dia']].astype(str).agg('-'.join, axis=1), errors='coerce', format='%Y-%m-%d')
weather_2023.drop(["ano", "mes", "dia"], axis=1, inplace=True)

In [18]:
#Eliminate columns that starts with 'v' and innecesary columns
pollution_2020.drop(columns=['punto_muestreo'] + [col for col in pollution_2020.columns if 'v' in col], inplace=True)
weather_2020.drop(columns= ['punto_muestreo'] + [col for col in weather_2020.columns if 'v' in col], inplace= True)

In [19]:
pollution_2021.drop(columns=['punto_muestreo'] + [col for col in pollution_2021.columns if 'v' in col], inplace=True)
weather_2021.drop(columns= ['punto_muestreo'] + [col for col in weather_2021.columns if 'v' in col], inplace= True)

In [20]:
pollution_2022.drop(columns=['punto_muestreo'] + [col for col in pollution_2022.columns if 'v' in col], inplace=True)
weather_2022.drop(columns= ['punto_muestreo'] + [col for col in weather_2022.columns if 'v' in col], inplace= True)

In [21]:
pollution_2023.drop(columns=['punto_muestreo'] + [col for col in pollution_2023.columns if 'v' in col], inplace=True)
weather_2023.drop(columns= ['punto_muestreo'] + [col for col in weather_2023.columns if 'v' in col], inplace= True)

**Confirm the update in datasets**

In [22]:
print("Dimensions Pollution Data after update:", pollution_2023.shape)
print("Dimensions Weather Data after update:", weather_2023.shape)

Dimensions Pollution Data after update: (63828, 28)
Dimensions Weather Data after update: (68913, 28)

**Para sql necesito que se añadan las filas de pollutant a la tabla weather teniendo en cuenta municipio, estacion y fecha**

In [23]:
pollution_2020.head()

,municipio,estacion,magnitud,h01,h02,h03,h04,h05,h06,h07,h08,h09,h10,h11,h12,h13,h14,h15,h16,h17,h18,h19,h20,h21,h22,h23,h24,fecha
0,102,1,1,"1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0",2020-01-01
1,102,1,6,"0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,4","0,3","0,3","0,3","0,3","0,3","0,4","0,4","0,4","0,4","0,4","0,4","0,4",2020-01-01
2,102,1,7,"1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","2,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0",2020-01-01
3,102,1,8,"8,0","8,0","7,0","6,0","6,0","6,0","7,0","6,0","5,0","5,0","5,0","5,0","5,0","5,0","5,0","5,0","6,0","7,0","8,0","8,0","8,0","9,0","10,0","8,0",2020-01-01
4,102,1,10,"8,0","15,0","13,0","11,0","12,0","16,0","17,0","20,0","11,0","2,0","1,0","1,0","9,0","9,0","8,0","7,0","14,0","22,0","22,0","16,0","16,0","17,0","17,0","17,0",2020-01-01

In [24]:
weather_2020.head()

,municipio,estacion,magnitud,h01,h02,h03,h04,h05,h06,h07,h08,h09,h10,h11,h12,h13,h14,h15,h16,h17,h18,h19,h20,h21,h22,h23,h24,fecha
0,102,1,81,"1,1",1,"1,1",1,"1,2","1,2","1,5","1,6","1,6",1,"0,4","0,8","1,3","1,6","1,5","0,8","0,8","1,3","0,7","0,2","0,3","0,9","0,7","0,4",2020-01-01
1,102,1,82,15,34,32,26,16,14,40,358,41,26,62,131,171,190,204,299,228,214,232,291,3,359,18,27,2020-01-01
2,102,1,83,"2,7","2,6","2,1","1,9","1,6","1,6",0,"0,1",2,"5,2","8,4","9,8","10,8","12,8","13,7","13,9","11,9","8,6","7,5","7,3","6,3","5,3","4,3","4,2",2020-01-01
3,102,1,86,86,87,89,91,92,92,96,96,87,76,65,60,60,53,48,43,53,63,68,68,74,81,86,85,2020-01-01
4,102,1,87,946,946,945,945,944,945,946,947,947,948,948,947,945,944,943,943,944,944,944,944,945,945,945,944,2020-01-01

**Concat weather and pollution datasets**

In [25]:
weather = pd.concat([weather_2020, weather_2021, weather_2022, weather_2023], axis = 0, ignore_index = True)
weather = weather.drop_duplicates()
weather.shape

(253006, 28)

In [26]:
weather.to_csv('../data/processed/weather.csv', index= False)

In [27]:
pollution = pd.concat([pollution_2020, pollution_2021, pollution_2022, pollution_2023], axis = 0, ignore_index = True)
pollution = pollution.drop_duplicates()
pollution.shape

(239073, 28)

In [28]:
pollution.to_csv('../data/processed/pollution.csv', index= False)

**Unify datasets using sql**

In [29]:
pollution = pd.read_csv('../data/processed/pollution.csv')
weather = pd.read_csv('../data/processed/weather.csv')

In [30]:
conn = sql.connect('../data/processed/air-q.db')
cursor = conn.cursor()

pollution.to_sql('pollution', conn, if_exists= 'replace', index= False)
weather.to_sql('weather', conn, if_exists= 'replace', index= False)

conn.close()

In [44]:
conn = sql.connect('../data/processed/air-q.db')
cursor = conn.cursor()

# query = '''
#     SELECT *
#     FROM weather
#     WHERE municipio=45;
# '''

query = '''
    SELECT *
    FROM weather
    INNER JOIN pollution ON weather.municipio = pollution.municipio;
'''

raw_airq = pd.read_sql_query(query, conn)
conn.close()

raw_airq = raw_airq.loc[:, ~raw_airq.columns.duplicated()]
raw_airq.head()

:

In [ ]:
# # Crear diccionario de los municipios de la Comunidad de Madrid
# municipal_dictionary = {
#     5: 'ALCALÁ DE HENARES',
#     6: 'ALCOBENDAS',
#     7: 'ALCORCÓN',
#     9: 'ALGETE',
#     13: 'ARANJUEZ',
#     14: 'ARGANDA DEL REY',
#     16: 'EL ATAZAR',
#     45: 'COLMENAR VIEJO',
#     47: 'COLLADO VILLALBA',
#     49: 'COSLADA',
#     58: 'FUENLABRADA',
#     65: 'GETAFE',
#     67: 'GUADALIX DE LA SIERRA',
#     74: 'LEGANÉS',
#     80: 'MAJADAHONDA',
#     92: 'MÓSTOLES',
#     102: 'ORUSCO DE TAJUÑA',
#     120: 'PUERTO DE COTOS',
#     123: 'RIVAS-VACIAMADRID',
#     133: 'SAN MARTÍN DE VALDEIGLESIAS',
#     148: 'TORREJÓN DE ARDOZ',
#     161: 'VALDEMORO',
#     171: 'VILLA DEL PRADO',
#     180: 'VILLAREJO DE SALVANÉS'
# }

In [ ]:
# # Crear diccionario de las magnitudes contaminantes
# pollutant = {
#     1: 'Dióxido de azufre (SO2)',
#     6: 'Monóxido de carbono (CO)',
#     7: 'Monóxido de nitrógeno (NO)',
#     8: 'Dióxido de nitrógeno (NO2)',
#     9: 'Partículas en suspensión < PM2,5 (PM2,5)',
#     10: 'Partículas en suspensión < PM10 (PM10)',
#     12: 'Óxidos de nitrógeno (NOx)',
#     14: 'Ozono (O3)',
#     20: 'Tolueno (CH3)',
#     22: 'Black Carbon (BC)',
#     30: 'Benceno (C6H6)',
#     42: 'Hidrocarburos totales',
#     44: 'Hidrocarburos no metánicos',
#     431: 'MetaParaXileno'
# }


# pollution_2020['municipio'] = pollution_2020['municipio'].map(municipal_dictionary)
# pollution_2020['magnitud'] = pollution_2020['magnitud'].map(pollutant)
# pollution_2020.head()

In [ ]:
# # Crear diccionario de las magnitudes meteorológicas
# weather_magnitudes = {
#     81: 'Velocidad del viento (m/s)',
#     82: 'Dirección del viento (Grd)',
#     83: 'Temperatura (ºC)',
#     86: 'Humedad relativa (%)',
#     87: 'Presión atmosférica (mbar)',
#     88: 'Radiación solar (W/m²)',
#     89: 'Precipitación (l/m²)',
# }


# weather_2020['municipio'] = weather_2020['municipio'].map(municipal_dictionary)
# weather_2020['magnitud'] = weather_2020['magnitud'].map(weather_magnitudes)
# weather_2020.head()

In [ ]:
# air_quality_2020 = pd.merge(pollution_2020, weather_2020, on= ["fecha", "municipio"])

# hour_pollution = [f'{col}_cont' if col.startswith("h") else col for col in pollution_2020.columns]
# hour_weather = [f'{col}_clima' if col.startswith("h") else col for col in weather_2020.columns]

# pollution_2020.columns = hour_pollution
# weather_2020.columns = hour_weather

# air_quality_2020 = pd.merge(weather_2020, pollution_2020, on= ["fecha", "municipio"])

# air_quality_2020

# Número de filas con magnitud "Dióxido de nitrógeno (NO2)
count_no2 = pollution_2020[pollution_2020['magnitud'] == 'Dióxido de nitrógeno (NO2)'].shape[0]
count_no2

- Alcala de henares: latitud 40.48205 y longitud -3.35996.
- Alcobendas: latitud 40.54746 y longitud -3.64197.
- Alcorcón: latitud 40.34582 y longitud -3.82487.
- Algete: latitud: 40.6149800 y longitud: -3.5332800
- Aranjuez: latitud 40.03108 y longitud -3.60246.
- Arganda del rey: latitud 40.30076 y longitud -3.43722
- El Atazar: latitud: 40.9333 y longitud: -3.46667
- Colmenar Viejo: latitud 40.65909 y longitud -3.76762.
- Collado Villaba: latitud 40.63506 y longitud -4.00486.
- Coslada: latitud 40.42378 y longitud -3.56129. 
- Fuenlabrada: latitud 40.28419 y longitud -3.79415.
- Getafe: latitud 40.30571 y longitud -3.73295. 
- Guadalix de la Sierra: latitud 40.7708873726963 y longitud -3.6776012313
- Leganes:	40.3273607712904,-3.7793069516
- Majadahonda: latitud 40.4738525865893 y longitud -3.8699340820
- Móstoles: latitud 40.3095534541817 y longitud -3.9005684364
- Orusco de Tajuna: latitud 40.2939972060512 y longitud -3.2113011173
- Rivas-Vaciamadrid: latitud 40.3510851699509 y longitud -3.5170123825
- Puerto de Cotos: latitud 40.823298 y longitud -3.962199°
- San-Martin de Valdeiglesias: latitud 40.3623132356877 y longitud -4.3439319018
- Torrejon de Ardoz: latitud 40.4674649068402 y longitud -3.4580456511
- Valdemoro: latitud 40.1807566367294 y longitud -3.6497825250
- Villa del Prado: latitud 40.269153264963 y longitud -4.30459675038
- Villarejo de Salvanes: latitud 40.1184071263897 y longitud -3.2694142410