In [9]:
# Import of libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
pd.set_option('display.max_columns', None)

In [11]:
pollution_madrid = pd.read_csv('../data/processed/pollution.csv')
pollution_madrid.head()

,municipio,estacion,magnitud,h01,h02,h03,h04,h05,h06,h07,h08,h09,h10,h11,h12,h13,h14,h15,h16,h17,h18,h19,h20,h21,h22,h23,h24,fecha
0,102,1,1,"1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0",2020-01-01
1,102,1,6,"0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,3","0,4","0,3","0,3","0,3","0,3","0,3","0,4","0,4","0,4","0,4","0,4","0,4","0,4",2020-01-01
2,102,1,7,"1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","2,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0","1,0",2020-01-01
3,102,1,8,"8,0","8,0","7,0","6,0","6,0","6,0","7,0","6,0","5,0","5,0","5,0","5,0","5,0","5,0","5,0","5,0","6,0","7,0","8,0","8,0","8,0","9,0","10,0","8,0",2020-01-01
4,102,1,10,"8,0","15,0","13,0","11,0","12,0","16,0","17,0","20,0","11,0","2,0","1,0","1,0","9,0","9,0","8,0","7,0","14,0","22,0","22,0","16,0","16,0","17,0","17,0","17,0",2020-01-01

In [13]:
pollution_madrid.shape

(239073, 28)

In [14]:
#Create a dictionary with the municipality code and its name
dicc_code_municip = {
    5: 'ALCALA DE HENARES',
    6: 'ALCOBENDAS',
    7: 'ALCORCON',
    9: 'ALGETE',
    13: 'ARANJUEZ',
    14: 'ARGANDA DEL REY',
    16: 'EL ATAZAR',
    45: 'COLMENAR VIEJO',
    47: 'COLLADO VILLALBA',
    49: 'COSLADA',
    58: 'FUENLABRADA',
    65: 'GETAFE',
    67: 'GUADALIX DE LA SIERRA',
    74: 'LEGANES',
    80: 'MAJADAHONDA',
    92: 'MOSTOLES',
    102: 'ORUSCO DE TAJUÃ‘A',
    120: 'PUERTO DE COTOS',
    123: 'RIVAS-VACIAMADRID',
    133: 'SAN MARTIN DE VELDEIGLESIAS',
    148: 'TORREJON DE ARDOZ',
    161: 'VALDEMORO',
    171: 'VILLA DEL PRADO',
    180: 'VILLAREJO DE SALVANES'
    }

In [ ]:
dicc_code_measure = {
    1: 'SO2',
    6: 'CO',
    7: 'NO',
    8: 'NO2',
    9: 'PM2.5',
    10: 'PM10',
    12: 'EL ATAZAR',
    14: 'COLMENAR VIEJO',
    20: 'COLLADO VILLALBA',
    22: 'COSLADA',
    30: 'FUENLABRADA',
    42: 'EL ATAZAR',
    44: 'COLMENAR VIEJO',
    431: 'COLLADO VILLALBA'
}